# Generated by Django 2.2.2 on 2019-11-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0010_auto_20191123_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form_12_Model',
        ),
        migrations.DeleteModel(
            name='Form_17_Model',
        ),
        migrations.DeleteModel(
            name='Form_1_Model',
        ),
        migrations.DeleteModel(
            name='Form_22_Model',
        ),
        migrations.DeleteModel(
            name='Form_2_Model',
        ),
        migrations.DeleteModel(
            name='Form_33_Model',
        ),
        migrations.DeleteModel(
            name='Form_3_Model',
        ),
    ]
