# Generated by Django 2.2.2 on 2019-11-26 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0012_trademarkaction1_trademarkaction2_trademarkparticulars_trademarkprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademarkprofile',
            name='action1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.TrademarkAction1'),
        ),
        migrations.AddField(
            model_name='trademarkprofile',
            name='action2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.TrademarkAction2'),
        ),
    ]
