# Generated by Django 2.2.2 on 2019-11-27 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0016_auto_20191126_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trademarkaction1',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='trademarkaction2',
            name='profile',
        ),
        migrations.CreateModel(
            name='Profile_Actions_Relative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.TrademarkAction1')),
                ('action2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.TrademarkAction2')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.TrademarkProfile')),
            ],
        ),
    ]
