# Generated by Django 2.2.2 on 2019-11-27 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0017_auto_20191127_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trademarkprofile',
            name='trademark_particulars',
        ),
        migrations.AlterField(
            model_name='profile_actions_relative',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.TrademarkProfile'),
        ),
    ]
