# Generated by Django 2.2.2 on 2019-11-27 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0019_auto_20191127_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trademarkprofile',
            name='action1',
        ),
        migrations.AddField(
            model_name='trademarkaction1',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_action1', to='Trademark_manager.TrademarkProfile'),
        ),
        migrations.AddField(
            model_name='trademarkaction2',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_action2', to='Trademark_manager.TrademarkProfile'),
        ),
    ]
