# Generated by Django 2.2.2 on 2019-11-27 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0021_auto_20191127_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_actions_relative',
            name='action1',
        ),
        migrations.RemoveField(
            model_name='profile_actions_relative',
            name='action2',
        ),
        migrations.RemoveField(
            model_name='profile_actions_relative',
            name='profile',
        ),
        migrations.AddField(
            model_name='trademarkparticulars',
            name='particulars',
            field=models.CharField(default='default particulars', max_length=50),
        ),
        migrations.AddField(
            model_name='trademarkprofile',
            name='action1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action1', to='Trademark_manager.TrademarkAction1'),
        ),
        migrations.AddField(
            model_name='trademarkprofile',
            name='action2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action2', to='Trademark_manager.TrademarkAction2'),
        ),
        migrations.AddField(
            model_name='trademarkprofile',
            name='trademark_particulars',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.TrademarkParticulars'),
        ),
    ]
