# Generated by Django 2.2.2 on 2019-11-27 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0022_auto_20191127_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trademarkprofile',
            name='trademark_particulars',
        ),
        migrations.AddField(
            model_name='trademarkprofile',
            name='particulars',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action1', to='Trademark_manager.TrademarkParticulars'),
        ),
    ]
