# Generated by Django 2.2.2 on 2019-11-27 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0023_auto_20191127_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademarkprofile',
            name='particulars',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trademark_particulars', to='Trademark_manager.TrademarkParticulars'),
        ),
    ]
