# Generated by Django 2.2.2 on 2019-11-27 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0027_auto_20191127_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_actions_relative',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.TrademarkProfile'),
        ),
        migrations.AlterField(
            model_name='trademarkprofile',
            name='action1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.TrademarkAction1'),
        ),
        migrations.AlterField(
            model_name='trademarkprofile',
            name='action2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.TrademarkAction2'),
        ),
        migrations.AlterField(
            model_name='trademarkprofile',
            name='particulars',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.TrademarkParticulars'),
        ),
    ]
