# Generated by Django 2.2.2 on 2019-11-27 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0028_auto_20191127_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_actions_relative',
            name='action1',
        ),
        migrations.RemoveField(
            model_name='profile_actions_relative',
            name='action2',
        ),
        migrations.RemoveField(
            model_name='profile_actions_relative',
            name='profile',
        ),
    ]
