# Generated by Django 2.2.2 on 2019-11-27 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0029_auto_20191127_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trademarkprofile',
            name='particulars',
        ),
    ]
