# Generated by Django 2.2.2 on 2019-11-28 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0032_auto_20191128_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademarkaction1',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.TrademarkProfile'),
        ),
        migrations.AddField(
            model_name='trademarkaction2',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.TrademarkProfile'),
        ),
    ]
