# Generated by Django 2.2.2 on 2019-11-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0033_auto_20191128_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_actions_relative',
            name='action1',
        ),
        migrations.RemoveField(
            model_name='profile_actions_relative',
            name='action2',
        ),
        migrations.RemoveField(
            model_name='profile_actions_relative',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='trademarkaction1',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='trademarkaction2',
            name='profile',
        ),
        migrations.DeleteModel(
            name='TrademarkParticulars',
        ),
        migrations.DeleteModel(
            name='Profile_Actions_Relative',
        ),
        migrations.DeleteModel(
            name='TrademarkAction1',
        ),
        migrations.DeleteModel(
            name='TrademarkAction2',
        ),
        migrations.DeleteModel(
            name='TrademarkProfile',
        ),
    ]
