# Generated by Django 2.2.2 on 2019-11-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Trademark_manager', '0034_auto_20191128_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrademarkProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='default client name', max_length=50)),
            ],
        ),
    ]
