# Generated by Django 2.2.2 on 2019-11-28 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0035_trademarkprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrademarkAction1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(default='default action', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrademarkParticulars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(default='default particulars', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='trademarkprofile',
            name='action1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.TrademarkAction1'),
        ),
        migrations.AddField(
            model_name='trademarkprofile',
            name='particulars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.TrademarkParticulars'),
        ),
    ]
