# Generated by Django 2.2.2 on 2019-12-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0037_auto_20191210_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademarkprofile',
            name='date_instruction_received',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
