# Generated by Django 2.1.11 on 2020-10-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0039_auto_20200225_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateprocurementaction',
            name='journal_no',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificateprocurementaction',
            name='journal_vol',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificateprocurementaction',
            name='registration_no',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationaction',
            name='trademark_class',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AlterField(
            model_name='trademarkprofile',
            name='incentive_due_clerk',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AlterField(
            model_name='trademarkprofile',
            name='registration_no',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AlterField(
            model_name='trademarkprofile',
            name='trademark_class',
            field=models.CharField(default='default value', max_length=50),
        ),
    ]
