# Generated by Django 2.1.11 on 2020-10-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0040_auto_20201001_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademarkprofile',
            name='applicable_official_fee',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AlterField(
            model_name='trademarkprofile',
            name='applicable_service_charge',
            field=models.CharField(default='default value', max_length=50),
        ),
    ]
