# Generated by Django 2.1.11 on 2020-10-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0041_auto_20201001_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademarkprofile',
            name='quicktellers_fee',
            field=models.CharField(default='default value', max_length=50),
        ),
    ]
