# Generated by Django 2.1.11 on 2020-10-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0043_auto_20201001_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trademarkprofile',
            name='ammendement_action',
        ),
        migrations.RemoveField(
            model_name='trademarkprofile',
            name='assignment_merger_action',
        ),
        migrations.RemoveField(
            model_name='trademarkprofile',
            name='certificate_procurement_action',
        ),
        migrations.RemoveField(
            model_name='trademarkprofile',
            name='change_name_address_action',
        ),
        migrations.RemoveField(
            model_name='trademarkprofile',
            name='reclassification_action',
        ),
        migrations.RemoveField(
            model_name='trademarkprofile',
            name='registration_action',
        ),
        migrations.RemoveField(
            model_name='trademarkprofile',
            name='renewal_action',
        ),
        migrations.RemoveField(
            model_name='trademarkprofile',
            name='search_action',
        ),
        migrations.AlterField(
            model_name='certificateprocurementaction',
            name='journal_no',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificateprocurementaction',
            name='journal_vol',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificateprocurementaction',
            name='registration_no',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationaction',
            name='trademark_class',
            field=models.CharField(default='default value', max_length=50),
        ),
        migrations.DeleteModel(
            name='TrademarkProfile',
        ),
    ]
