# Generated by Django 2.1.11 on 2020-10-03 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0044_auto_20201003_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrademarkProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicable_official_fee', models.CharField(default='default value', max_length=50)),
                ('applicable_service_charge', models.CharField(default='default value', max_length=50)),
                ('trademark_class', models.CharField(default='default value', max_length=50)),
                ('clerk_responsible', models.CharField(default='default value', max_length=50)),
                ('clients_email_address', models.CharField(default='default value', max_length=50)),
                ('clients_id', models.CharField(default='default value', max_length=50)),
                ('clients_address', models.CharField(default='default value', max_length=50)),
                ('clients_contact_person', models.CharField(default='default value', max_length=50)),
                ('client_ref_no', models.CharField(default='default value', max_length=50)),
                ('correspondence_date', models.DateField()),
                ('current_instruction', models.CharField(default='default value', max_length=50)),
                ('current_status', models.CharField(default='default value', max_length=50)),
                ('date_instruction_received', models.DateField()),
                ('date_current_instruction', models.DateField()),
                ('date_completed_job_received', models.DateField()),
                ('date_incoming_abj_schedule', models.DateField()),
                ('date_outgoing_abj_schedule', models.DateField()),
                ('filing_receipt', models.CharField(default='default value', max_length=50)),
                ('goods', models.CharField(default='default value', max_length=50)),
                ('incentive_due_clerk', models.CharField(default='default value', max_length=50)),
                ('lawyer_responsible', models.CharField(default='default value', max_length=50)),
                ('month_incoming_schedule', models.CharField(default='default value', max_length=50)),
                ('month_outgoing_schedule', models.CharField(default='default value', max_length=50)),
                ('name_of_client', models.CharField(default='default value', max_length=50)),
                ('name_of_proprietor', models.CharField(default='default value', max_length=50)),
                ('official_fee_ctc', models.CharField(default='default value', max_length=50)),
                ('official_fee_late_renewal_penalty', models.CharField(default='default value', max_length=50)),
                ('official_fee_merger', models.CharField(default='default value', max_length=50)),
                ('official_fee_registered_user', models.CharField(default='default value', max_length=50)),
                ('our_ref_no', models.CharField(default='default value', max_length=50)),
                ('proprietors_address', models.CharField(default='default value', max_length=50)),
                ('quicktellers_fee', models.CharField(default='default value', max_length=50)),
                ('registration_no', models.CharField(default='default value', max_length=50)),
                ('trademark_description', models.CharField(default='default value', max_length=50)),
                ('ammendement_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.AmendementAction')),
                ('assignment_merger_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.AssignmentMergerAction')),
                ('certificate_procurement_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.CertificateProcurementAction')),
                ('change_name_address_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.ChangeName_AddressAction')),
                ('reclassification_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.ReclassificationAction')),
                ('registration_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.RegistrationAction')),
                ('renewal_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.RenewalAction')),
                ('search_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trademark_manager.SearchAction')),
            ],
        ),
    ]
