# Generated by Django 2.1.11 on 2020-10-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trademark_manager', '0046_auto_20201003_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amendementaction',
            old_name='date_amendement_received',
            new_name='date_amendment_received',
        ),
    ]
