# Generated by Django 2.2.2 on 2019-09-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form_33_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trademark_number', models.CharField(max_length=30)),
                ('trademark_class', models.CharField(max_length=30)),
                ('trademark_date', models.DateField()),
            ],
        ),
    ]
