# Generated by Django 2.2.2 on 2019-09-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patent_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form_33_Model',
        ),
    ]
