# Generated by Django 2.1.11 on 2020-06-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patent_manager', '0003_amendmentaction_assignmentmergeraction_changeofaddressaction_changeofnameaction_ctcaction_patentpart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amendmentaction',
            old_name='date_ammendment_instruction_received',
            new_name='date_amendment_instruction_received',
        ),
    ]
