# Generated by Django 2.1.11 on 2020-09-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patent_manager', '0004_auto_20200602_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentmergeraction',
            name='date_abuja_instructed_assignment',
            field=models.DateField(),
        ),
    ]
