# Generated by Django 2.1.11 on 2020-09-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patent_manager', '0005_auto_20200916_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeofaddressaction',
            name='date_received_change_of_address_certificate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ctcaction',
            name='date_applied_for_ctc',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='procurementofcertificateaction',
            name='date_cert_procured',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='procurementofcertificateaction',
            name='date_cert_procurement_due',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='procurementofcertificateaction',
            name='date_procurement_instructed',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registrationaction',
            name='month_registration_instruction_received',
            field=models.CharField(default='default value', max_length=50),
        ),
    ]
